### ISSUE TITLE
How to use jcohy-ali-oss gradle plugin

### ISSUE THREAD

**Issue by adrienbusin** [jcohy/jcohy-gradle-plugins#37]
Following this documentation not working properly : 
https://github.com/jcohy/jcohy-gradle-plugins/blob/main/src/docs/asciidoc/alioss.adoc

First ->  classpath("io.github.jcohy.gradle:jcohy-ali-oss:${version}") doesn't exists on mavenCentral

Second if I use classpath("io.github.jcohy:jcohy-ali-oss:3.0.0.6") I have this issue -> 

A problem occurred configuring root project .
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve io.github.jcohy:jcohy-ali-oss:3.0.0.6.
     Required by:
         project :
      > Cannot choose between the following variants of io.github.jcohy:jcohy-ali-oss:3.0.0.6:
          - javadocElements
          - sourcesElements
        All of them match the consumer attributes:
          - Variant 'javadocElements' capability io.github.jcohy:jcohy-ali-oss:3.0.0.6:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'javadoc' but wasn't required.
                  - Required org.gradle.jvm.version '11' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'sourcesElements' capability io.github.jcohy:jcohy-ali-oss:3.0.0.6:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'sources' but wasn't required.
                  - Required org.gradle.jvm.version '11' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

**Comment by jiachao23** [comment]
@adrienbusin 

Due to organizational adjustments, jcohy-ali-oss gradle plugins its group changed from ` com.jcohy.gradle`  to `io.github.jcohy.gradle`.

The `io.github.jcohy.gradle` 3.0.0.x version requires minimum jdk version 17. 

If you are using a lower version，you can use `com.jcohy.gradle` group:

```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("com.jcohy.gradle:jcohy-ali-oss:0.0.6")
	}
}
apply plugin: "com.jcohy.oss"
```


this is the artifact url: https://repo.maven.apache.org/maven2/com/jcohy/gradle/jcohy-ali-oss/

Thanks!
